### ISSUE TITLE
Tools and guide?

### ISSUE THREAD

**Issue by liamnajor** [DaruniasJoy/OoT-Custom-Sequences#102]
I am trying to make custom tracks for a streamer I watch. I have about 5 different midis that I've already tested and converted into the OOT soundfont. I tried to use seq64 but it didn't export the right file type. I do not care if you want to add said tracks to this repository, but would like to know how you generated these files (I already read the old issues, there's no discord link I could find in that spreadsheet)

**Comment by DaruniasJoy** [comment]
There is a Discord link in the Spreadsheet --> has 3 tabs below  --> click on information you'll find the link
