### ISSUE TITLE
Lands of Lore Southland Forest

### ISSUE THREAD

**Issue by RandomizerFan** [DaruniasJoy/OoT-Custom-Sequences#118]
If it's at all possible, may I request that the song that plays for Southland Forest in Lands of Lore: The Throne of Chaos be converted to a .seq file? I've included all of the files below. Sorry if it causes any inconveniences, but I could only find the Japanese version of the song. I hope it doesn't cause any trouble.
[Lands of Lore Southland Forest.zip](https://github.com/DaruniasJoy/OoT-Custom-Sequences/files/7257374/Lands.of.Lore.Southland.Forest.zip)

**Comment by DaruniasJoy** [comment]
will take a look at it as soon as we got time for it.

**Comment by RandomizerFan** [comment]
Excellent! Thank you so much!!

**Comment by RandomizerFan** [comment]
Sorry, but you were taking so long and I figured you didn't/don't want to do it. My apologies for asking.

**Comment by DaruniasJoy** [comment]
thats not the case , our backlog of requests is just damn long. and we do this as our hobby so this can take months to be added,

**Comment by RandomizerFan** [comment]
Oh, okay. I apologize, it was a stupid request on my part, anyway.
