### ISSUE TITLE
Lands of Lore: The Throne of Chaos Southland Forest Lower Opinwood Music

### ISSUE THREAD

**Issue by RandomizerFan** [DaruniasJoy/OoT-Custom-Sequences#126]
If it's possible, can you check to see if it's possible to add this into a potential song for the OoT Randomizer to plug into a seed, please?
[Lands of Lore Southland Forest.zip](https://github.com/DaruniasJoy/OoT-Custom-Sequences/files/7477357/Lands.of.Lore.Southland.Forest.zip)

**Comment by DaruniasJoy** [comment]
will check on it when we got time :)
