### ISSUE TITLE
2 King's Field songs?

### ISSUE THREAD

**Issue by Herowho42** [DaruniasJoy/OoT-Custom-Sequences#16]
Would it be possible to add 2 particular songs from King's Field: The Ancient City? I would request more, but I have no idea how tedious the process is, the ones I mostly want are the Damp Tomb and the City/Village Ruins themes.

**Comment by darkangel93x** [comment]
If you can provide me some Midi Files to work with eventually. I didnt find anything useful yet.

**Comment by Herowho42** [comment]
[King's Field MIDIs.zip](https://github.com/DaruniasJoy/OoT-Custom-Sequences/files/3774367/King.s.Field.MIDIs.zip)
These are the best ones I could find.

**Comment by darkangel93x** [comment]
will work on this in the next days , hope i get it worked out :)

**Comment by Herowho42** [comment]
Thank you so much. King's Field is so great and I can't believe I'm going to be able to hear some of it's music in OoT. I can only imagine how tedious the process of changing the Midi notes to OoT instruments is. Again, thank you.

**Comment by DaruniasJoy** [comment]
i close this issue but its still on our list. :)
