### ISSUE TITLE
Add my music

### ISSUE THREAD

**Issue by LuigiXHero** [DaruniasJoy/OoT-Custom-Sequences#161]
Made my pack a couple months after your initial commit to this was made, but I don't remember seeing it when I searched around so it must've been private at the time?

Anyways it's here: https://github.com/LuigiXHero/OoT-Randomizer-Music-Pack

If you do decide to merge it all in i'll private it.

I can also make a pull request and fix the formatting by putting them in folders if you like instead but i'm pretty busy atm, so dunno when that'd be.

**Comment by DaruniasJoy** [comment]
will check on it the next days. :)

**Comment by DaruniasJoy** [comment]
https://prnt.sc/qHDdKzNZXaXC Pretty Sure TP and WW are self-explanatory but i ask nonetheless what games are those ?

**Comment by LuigiXHero** [comment]
Yeah its twilight princess and wind waker, I wrote it out fully in the git Readme. As for windmill remix it's a old remix of song of storms from OOT to be more of a dungeon song.

**Comment by DaruniasJoy** [comment]
thanks added the remaining stuff so i close this
