### ISSUE TITLE
A couple of song requests

### ISSUE THREAD

**Issue by RevanXVIV** [DaruniasJoy/OoT-Custom-Sequences#18]
Hi! I don't know if this is still being updated or not, but I use the current pack for OoT custom sequences VERY frequently and would like to request a few songs I feel would make some really good additions, if it's not too much trouble that is.

Well my requests are: Lavender Town, Halo Main Theme/Warthog Run. Pokemon Alpha Sapphire Team Leader battle, Rayquaza's battle theme, Tiny Woods (Pokemon Mystery Dungeon Rescue Team games), Mt Steel (PMD Rescue Team), Sky Tower (PMD Rescue Team), Magma Cavern (PMD Rescue Team), Duel of the Fates(Star Wars), and Battle of the Heroes (Star Wars)

EDIT: BTW I can find and provide ALL the midi files required for this. If I have issues finding some songs I'll let you know :)

EDIT 2: Ok so I found most of the midis for the songs I listed, some don't exist so there are a few replacements, only about 3 or 4 I hope that's not an issue, if it is I can remove them. Just let me know when you want them and I'll post a link to the zip file.

**Comment by darkangel93x** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSe17AuRzGGx7WaaX70hggeAYDD-NmXA9rOI2QIKbPCQIhR2tg/viewform please use this as Request platform.

makes it easier for us and we have an overview without having to click every single request :)

thanks in advance

**Comment by RevanXVIV** [comment]
Thanks! I'll post my request there then, sorry about the mixup. :)

**Comment by darkangel93x** [comment]
post the zip with one request we figure out the rest :)

**Comment by RevanXVIV** [comment]
Perfect so I'll just post the first song in the file for the required fields :)

**Comment by darkangel93x** [comment]
do me a favor, request all songs one by one. the sonic one has the midis attached which is perfect :)
the other request **_DO NOT_** need another midi attached.

**Comment by RevanXVIV** [comment]
Ok so just request each song individually with the hd version accompanying it? I hope I got that right, ok will do. I'll start uploading in about 5 minutes. Also when any of the songs are finished being converted, assuming you do them one at a time and not all at once, will you just let me know in the chain please?

**Comment by darkangel93x** [comment]
perfect ty. they get uploaded once were done with a bunch of songs :)

**Comment by RevanXVIV** [comment]
Oh boy! I hope mephiles whisper gets in, I'd love to get a seed with that as my shadow temple music! By description I assume you mean on the github main page for the project.

**Comment by RevanXVIV** [comment]
Hey I've just got a quick question about the process, how long does it usually take for one song listed as "WIP" to be finished and uploaded to the pack? I've been keeping an eye on the spreadsheet and noticed my Lavender town request is currently "WIP"

**Comment by DaruniasJoy** [comment]
Lavender Town should be completely done. I will close this request since they are on the sheet. Hope you will like it.

Also be aware due to limitations the requests you send either take longer, or have been ruled out for being able to do them. It can happen but dont be discouraged to request stuff if you have something in mind.
