### ISSUE TITLE
Tal Tal Heights Seq

### ISSUE THREAD

**Issue by rchrm5** [DaruniasJoy/OoT-Custom-Sequences#20]
Hello, not sure if it is possible to pitch up parts of the Tal Tal Heights arrangement from Link's Awakening, but it does not reach the higher pitch levels and I wasn't sure if it would be possible to edit the sequence to make this sound more like the original? Thanks!

**Comment by darkangel93x** [comment]
i wanted to redo that anyway. will see what is possible then :)

**Comment by rchrm5** [comment]
Thanks!

**Comment by DaruniasJoy** [comment]
Got replaced today by a new version based on the Remake. Hope you will enjoy that.

**Comment by rchrm5** [comment]
Thanks so much! I will try it out after work today.

**Comment by rchrm5** [comment]
The new version you added is amazing! Thanks for much for uploading it!
