### ISSUE TITLE
Bowser in the Dark World Sequence Request

### ISSUE THREAD

**Issue by rchrm5** [DaruniasJoy/OoT-Custom-Sequences#21]
Hello, 

I put in a request a couple days ago for the subject song to be added. I've attached a .seq file (hopefully it retains all of the data since I had to save as a .txt file) from the Majora's Mask Randomizer, and it works fairly well, except the background percussion sounds too high. Would you be able to tweak this to edit the background to lower it? (0x22 works quite well with this track). If you believe information is missing, let me know and I will try to save as a more robust file type. Thanks!

[sm64-bitdw.txt](https://github.com/DaruniasJoy/OoT-Custom-Sequences/files/4533839/sm64-bitdw.txt)

**Comment by DaruniasJoy** [comment]
closing this issue but be assured its still on our request list :)

**Comment by rchrm5** [comment]
Thank you for all of your hard work on this! I use these sequences all the
time and it has made the gameplay experience so much better. Merry
Christmas.
