### ISSUE TITLE
Volume/Velocity Quality Control needed

### ISSUE THREAD

**Issue by raekuul** [DaruniasJoy/OoT-Custom-Sequences#251]
A twitch streamer that I follow has recently been complaining about inconsistent track volumes and has started manually removing sequence files that are distractingly or damagingly loud (which ends up being a counter-recommendation to this project and the sister project).  Is there a process in place for track QC beyond "it doesn't crash the game?"  I realize that normalizing midi files and therefore seq files is not exactly an easy thing to do (since it can't be done via tags like mp3) but there should at least be an attempt at not driving players away from the music pack.

**Comment by DaruniasJoy** [comment]
easiest solution ? report the tracks with issues to us.

i gave the recommendation to do a volume check outside of links house . Because if you can clearly hear the waterfall its definitely not too loud.

**Comment by NewSoupVi** [comment]
I wanted to give an update on this.

Thanks to new software that allows us to preview the songs more easily, Pull Requests from now on will check every song, at least in my case. I'm not sure about DA or TSD.
More importantly, I have made a tool to quickly change the volume of a song, which allows us maintainers to make changes to the volume without having to chase up the original owners or spend a long time doing it ourselves. So please report the songs that cause issues, from now on something will actually be done about it in due time.
