### ISSUE TITLE
Copyrighted music in this pack

### ISSUE THREAD

**Issue by ghost** [DaruniasJoy/OoT-Custom-Sequences#393]
Both song of healing and battle against a true hero have given me copyright claims on my youtube streams, assuming the other undertale songs would too.

**Comment by DaruniasJoy** [comment]
who the fuck claims Song of Healing ? Thats Majora's Mask music and unless its nintendo its a false claim.
as for Undertale we can move that to GO. Though the claim for that does not really matter if your streams are non commercially.

**Comment by ghost** [comment]
It seems it wasnt the official nintendo version but a cover "song of healing by ottawa guitar trio"

**Comment by DaruniasJoy** [comment]
moved deltarune and song of healing are false claims so i dont bother.
