### ISSUE TITLE
songs not working

### ISSUE THREAD

**Issue by jakajaka09** [DaruniasJoy/OoT-Custom-Sequences#397]
If I put the songs into the randomizer file and I patch the rom and launch the game the songs won't work

**Comment by DaruniasJoy** [comment]
Thats.... very unspecific? Which version of the randomizer are you using? 

for 7.1.129 or older u need the old .meta .seq files which u find here : [here](https://github.com/DaruniasJoy/OoT-Custom-Sequences/tree/Old-Custom-Music-Format)

if u are up to date u need to use this : [here](https://github.com/DaruniasJoy/OoT-Custom-Sequences/tree/Custom-Music-2.0)
