### ISSUE TITLE
Method?

### ISSUE THREAD

**Issue by DrNjitram** [DaruniasJoy/OoT-Custom-Sequences#92]
Me and a friend have been tinkering around with converting midi files to seq files and using them in ocarina of time randomisers. 
However all attemps came back mangled.

We have been using seq64 and midis from a few sites. Some instruments have been missing, and many notes are dropped.

Is there a setting we are missing or is there a better way to convert midis to (a)seq?

**Comment by DaruniasJoy** [comment]
Join our discord you find it linked in the spreadsheet there people can help you with everything :)
